# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: loa.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'loa.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tloa.proto\x12\x03loa\"\x83\x01\n\x08\x45nvelope\x12\x16\n\x0eschema_version\x18\x01 \x01(\r\x12\x1b\n\x05state\x18\x02 \x01(\x0b\x32\n.loa.StateH\x00\x12\x1d\n\x06\x66rames\x18\x03 \x01(\x0b\x32\x0b.loa.FramesH\x00\x12\x1b\n\x05\x65vent\x18\x04 \x01(\x0b\x32\n.loa.EventH\x00\x42\x06\n\x04\x62ody\"\xdf\x03\n\x05State\x12\x0c\n\x04mood\x18\x01 \x01(\t\x12\x13\n\x0bmood_set_at\x18\x02 \x01(\x01\x12\x12\n\nring_state\x18\x03 \x01(\t\x12\x15\n\rpending_event\x18\x04 \x01(\t\x12\x11\n\toled_mode\x18\x05 \x01(\t\x12\x11\n\toled_text\x18\x06 \x01(\t\x12\x10\n\x08oled_dim\x18\x07 \x01(\x08\x12\x11\n\tripperdoc\x18\x08 \x01(\x08\x12\x16\n\x0eripperdoc_page\x18\t \x01(\t\x12\x11\n\tcondition\x18\n \x01(\t\x12\x10\n\x08pir_high\x18\x0b \x01(\x08\x12\x11\n\tpir_count\x18\x0c \x01(\r\x12\x13\n\x0bpir_last_ts\x18\r \x01(\x01\x12\x15\n\rpir_last_hold\x18\x0e \x01(\x01\x12\x13\n\x06snr_cm\x18\x0f \x01(\x01H\x00\x88\x01\x01\x12\x11\n\tsnr_count\x18\x10 \x01(\r\x12\x13\n\x06temp_c\x18\x11 \x01(\x01H\x01\x88\x01\x01\x12\x14\n\x07hum_pct\x18\x12 \x01(\x01H\x02\x88\x01\x01\x12\x0f\n\x07temp_ts\x18\x13 \x01(\x01\x12\x19\n\x0cpressure_hpa\x18\x14 \x01(\x01H\x03\x88\x01\x01\x12\x0f\n\x07\x62\x61ro_ts\x18\x15 \x01(\x01\x42\t\n\x07_snr_cmB\t\n\x07_temp_cB\n\n\x08_hum_pctB\x0f\n\r_pressure_hpa\"$\n\x06\x46rames\x12\x0c\n\x04\x66\x61\x63\x65\x18\x01 \x01(\x0c\x12\x0c\n\x04ring\x18\x02 \x01(\x0c\"x\n\x05\x45vent\x12\n\n\x02ts\x18\x01 \x01(\x01\x12\x0c\n\x04kind\x18\x02 \x01(\t\x12&\n\x06\x64\x65tail\x18\x03 \x03(\x0b\x32\x16.loa.Event.DetailEntry\x1a-\n\x0b\x44\x65tailEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'loa_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EVENT_DETAILENTRY']._loaded_options = None
  _globals['_EVENT_DETAILENTRY']._serialized_options = b'8\001'
  _globals['_ENVELOPE']._serialized_start=19
  _globals['_ENVELOPE']._serialized_end=150
  _globals['_STATE']._serialized_start=153
  _globals['_STATE']._serialized_end=632
  _globals['_FRAMES']._serialized_start=634
  _globals['_FRAMES']._serialized_end=670
  _globals['_EVENT']._serialized_start=672
  _globals['_EVENT']._serialized_end=792
  _globals['_EVENT_DETAILENTRY']._serialized_start=747
  _globals['_EVENT_DETAILENTRY']._serialized_end=792
# @@protoc_insertion_point(module_scope)
